services:
  - type: web
    name: nexusapi
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.8"
      - key: DATABASE_URL
        value: postgresql://nexusdb_flst_user:jtSySRr9sdfnmfFPx9mBvyGamLDYyrGb@dpg-d8kitbeq1p3s73fl9dr0-a/nexusdb_flst
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
    healthCheckPath: /health
